Ticket2338 instron
ISISComputingGroup/EPICS-instron pull request #3
Opened 2017-06-20 15:45 UTC by Tom-Willemsen

See https://github.com/ISISComputingGroup/IBEX/issues/2338

2017-09-04 12:24 UTC, Tom-Willemsen commented on instronSup/devinstron.proto
> +    out "C904,0";
On inspection of network traces this was the wrong command previously.

2017-09-04 12:24 UTC, Tom-Willemsen commented on instronSup/devinstron.proto
> +	disableWatchdog;
This is necessary to prevent the rig from tripping the hydraulics.

2017-09-04 14:18 UTC, AdrianPotter requested changes
Tiny bit of clear up

2017-09-04 14:18 UTC, AdrianPotter commented on instronSup/devinstron.proto
> +#OutTerminator = ";";
As discussed, please remove unused code

2017-09-05 10:53 UTC, AdrianPotter approved these changes

2017-09-05 12:26 UTC, merged